---
development:
  DB_FILENAME: app/infrastructure/database/local/dev.db
  COUNTRIES_FILE_PATH: app/infrastructure/local_files/json_files/countries.json
  CATEGORIES_FILE_PATH: app/infrastructure/local_files/json_files/categories.json
  IMAGE_PATH: app/presentations/views/assets/img/

test:
  DB_FILENAME: app/infrastructure/database/local/test.db
  COUNTRIES_FILE_PATH: app/infrastructure/local_files/json_files/countries.json
  CATEGORIES_FILE_PATH: app/infrastructure/local_files/json_files/categories.json
  IMAGE_PATH: app/presentations/views/assets/img/
  APP_HOST: http://localhost:9000

production:
  DB_FILENAME: app/infrastructure/database/local/dev.db
  COUNTRIES_FILE_PATH: app/infrastructure/local_files/json_files/countries.json
  CATEGORIES_FILE_PATH: app/infrastructure/local_files/json_files/categories.json
  IMAGE_PATH: app/presentations/views/assets/img/